### ISSUE TITLE
remove() remove all items in file

### ISSUE THREAD

**Issue by Tolomaj** [Lenn-xsr/db-local#12]
if i try to remove one item it remove all items in file.
const fItem = Item.find({ _id: 1 })
fItem.remove()

i dont know if this is feature or bug but if this is feature haw can i remove only one item?

**Comment by Lenn-xsr** [comment]
All items from the past that had the same _id will be removed, as the property is unique in the database, it is a filter and removes the _id.

The function we use to remove:

`Model.find((obj) => obj._id !== _id);`

If for some reason you have more than one equal _id registered in the database and it is not being returned in the find, it will be removed together..

**Comment by Tolomaj** [comment]
sorry, Just where did you get the object Model?

**Comment by Lenn-xsr** [comment]
See the [documentation](https://lenn.gitbook.io/db-local/schema), the Model would be the return of creating a Schema

**Comment by Tolomaj** [comment]
I found only .remove() in the documentation but no .filter() function.
The same says node.js `TypeError: ContentPool.filter is not a function`.
And nodejs only sees these features:
`{
  find: [Function: find],
  create: [Function: create],
  remove: [Function: remove],
  update: [Function: update],
  replaceModel: [Function: replaceModel]
}`.
Is there any diferent way to remove only one item?

**Comment by Lenn-xsr** [comment]
Sorry, I ended up typing filter instead of find

Here below I will give you some examples that you can use to remove just one item:

Obs.: Make sure your package version is at the latest [ [1.5.3](https://www.npmjs.com/package/db-local) ]
```js
User.remove((user) => user.bag.weapons.length >= 2); // This function example removes multiple objects at once, be careful with usage.
User.remove({ _id: 1 });
User.remove(1);

User.find({ _id: 1 }).remove()
```

**Comment by Tolomaj** [comment]
Wery mutch thanks.
