### ISSUE TITLE
Combine tables

### ISSUE THREAD

**Issue by CarmenLexa** [Lenn-xsr/db-local#13]
how can I combine several tables as well as an INNER JOIN in SQL  ?
if in mongo it is possible to create references using the ID
id_script: { type:Schema.Types.ObjectId, ref: "Script"},
how can I do it with the module?

**Comment by Lenn-xsr** [comment]
We still don't have this functionality, I'm going to prioritize and apply this reference system in the "find" function..

From what I thought, it would work more or less like this:

```js
<Schema>.find({ _id: 1, creator: { $ref: "creators", "$id": 2 })
```

That way, you would get a return like this:

```js
{
  "_id": 1,
  "creator": {
    "_id": 2,
    // .. other fields
  }
}
```

**Comment by CarmenLexa** [comment]
is exactly what I am looking for, I am even willing to make a donation to you in bitcoin if you can do it as soon as possible please.

**Comment by Lenn-xsr** [comment]
This functionality has been added, it works exactly as I described before.

There will still be some functionality updates to make it even better.

**Comment by CarmenLexa** [comment]
thanks for adding it, now I am facing a little problem.
I try to join 3 tables 
try to do the following, but it does not work

 const values = User.find({ _id: parseInt(req.params.id)},(user) => {
            return { books:{ $ref: "Books", $id: parseInt(user.id_book)},comments:{ $ref: "Comments", $id: parseInt(user.id_comment)}}
 }); 

how can I perform a search by joining more tables when I only have one ID?

**Comment by Lenn-xsr** [comment]
I added a new functionality, to facilitate the reuse of data.

First, update db-local to the latest version [1.5.3](https://www.npmjs.com/package/db-local)..

After updating, you can follow the example below:

```js
User.find({
  _id: 1,
  books: { $ref: "Books", $id: { $data: "id_book" } }, // or: books: { $ref: "Books", $id: "$data.id_book" }
  comments: { $ref: "Comments", $id: { $data: "id_comment" } }
})
```

Any questions or errors, I'll be at your disposal :D

**Comment by CarmenLexa** [comment]
thank you for your help, but I see another problem in doing this.

const datas = User.find({
  books: { $ref: "Books", $id: { $data: "id_book" } }, 
  comments: { $ref: "Comments", $id: { $data: "id_comment" } }
})

this is supposed to get all the data that exists with each related table added, but it doesn't work, it only works if the ID is added

**Comment by CarmenLexa** [comment]
another error that I saw, is that when I make several queries using GET from express, I get an undefined when relating to other tables for example like this

User.find({
  _id: 1,
  books: { $ref: "Books", $id: { $data: "id_book" } }, // or: books: { $ref: "Books", $id: "$data.id_book" }
  comments: { $ref: "Comments", $id: { $data: "id_comment" } }
})
if I make several GET requests I get an undefined return on the books and comments keys

**Comment by Lenn-xsr** [comment]
Could you please attach the base file of your bank, along with an example of the data that is saved?

I would like to do a more in-depth test using the same scenario as yours

Obs.: It usually returns undefined when it doesn't find any related data in the reference tables.

**Comment by CarmenLexa** [comment]
I am noticing that when doing a GET that returns all data with two related tables and then doing a GET BY ID with the same tables, the values cross and GET BY ID returns the values of the first query with the keys, having specified other keys in the example GET BY ID query:

GET query
` 
const datas = User.find();
        const output = datas.map(item => {
            const rows = User.find({_id: parseInt(item._id),id_book:{ $ref: "Books", $id: parseInt(item.id_book)},id_comments: { $ref: "Comments", $id: parseInt(item.id_comments)}});
            return rows;
        });
`
this has to come back to me like this 

`{
  _id: 1648603362287,
  user_name: 'test',
  id_book: {
    _id: 1648601428691,
    alias: 'doom',
  },
  id_comments:undefined,
}`

that is the expected result and it works but now
do a search by ID

`
 const rows = User.find({
            _id:parseInt(req.params.id),
            tb_book: { $ref: "Books", $id: { $data: "id_book" } },
            tb_comments: { $ref: "Comments", $id:  {  $data: "id_comments"} } 
        });
`
this is the result

`{
  _id: 1648603362287,
  user_name: 'test',
  id_book: {
    _id: 1648601428691,
    alias: 'doom',
  },
  id_comments:undefined,,
  tb_book:undefined,
  tb_comments:undefined
}
`
the above values are maintained even though it is a different query within a different function, this is very rare. 
i am using in my express server the nodemon module, I don't know if that's the problem or if the values are stored in memory.
or you may have to declare a new variety 
`
const User = Schema("User",user_schema);`

in each function?

**Comment by Lenn-xsr** [comment]
I will check and do some tests using the same find base, but I already recommend adding one more thing when running with nodemon, because it detects changes in the database jsons and ends up restarting the application and this can cause bugs.

In your start or dev function, inside the package, recommend starting nodemon like this:

```json
"scripts": {
  "dev": "nodemon ./src/app.js --ignore src/databases/*",
  "start": "node ./src/app.js"
}
```

Just add to the end of nodemon the argument `--ignore **\<path where the database files are\>**\/*

**Comment by CarmenLexa** [comment]
The error is if you use the same id_book key to store the values of the whole table that makes the data lost, I think it was a mistake of mine :/
I try to do the following 

const output = User.find({id_book: { $ref: "Books", $id: { $data: "id_book" } }});

for all values related to the Book table
table, but it returns a null value

**Comment by Lenn-xsr** [comment]
I did a test locally, and I had a normal return, what I saw in your code is that you were putting the name of the object where the reference would be received, as the same name that already exists in the user object.

So, I recommend following the code below, I tested it and it worked :D

```js
const dbLocal = require("db-local");
const { Schema } = new dbLocal({ path: "./databases" });

const Book = Schema("Books", {
  _id: { type: Number, required: true },
  name: { type: String, default: "Book" },
});

const Comment = Schema("Comments", {
  _id: { type: Number, required: true },
  name: { type: String, default: "Comment" },
});

const User = Schema("User", {
  _id: { type: Number, required: true },
  username: { type: String, default: "Customer" },
  id_book: { type: Number },
  id_comments: { type: Number },
});

const datas = User.find();
const output = datas.map((item) => {
  const rows = User.find({
    _id: parseInt(item._id),
    books: { $ref: "Books", $id: "$data.id_book" },
    comments: { $ref: "Comments", $id: "$data.id_comments" },
  });
  return rows;
});

console.log(output);
```
Result
![image](https://user-images.githubusercontent.com/55673351/160917577-c7768076-04a7-4d73-a7d0-543ce6d9fc84.png)

**Comment by Lenn-xsr** [comment]
Another problem that you may encounter is that for now, the method I use to get the reference will always return only one object ( even because there can only be one _id )

If the system you are making is a book system, I recommend making an object for each user in the books part, and in that object, having an array with his books :D

```js
const Book = Schema("Books", {
  _id: { type: Number, required: true },
  books: Array
});
```

**Comment by Lenn-xsr** [comment]
I ended up doing another update, now you can shorten your code and do like the example below

Update the package again to the latest version.. [ 1.5.4 ]
```js
const output = User.find({ book: { $ref: "Books", $id: { $data: "id_book" } } });
```
Now you can have a return with multiple users, in your case, just don't pass the `_id` initially

**Comment by CarmenLexa** [comment]
Thanks for your help, I already corrected several errors now I see that something else is missing to add to the "find" function is the use of conditionals adding multiple tables.

 const datas = User.find((books) => books.count_commets>0,{ tb_comments:{ $ref: "Comments", $id: { $data: "id_comments" }}});
 console.log(datas);

try to do this but it doesn't work the only way it works is to do it like this

const datas = User.find((books) => books.count_commets>0);
const output = datas.map(item => {
            const rows = User.find({_id: parseInt(item._id),tb_comments: { $ref: "Comments", $id: parseInt(item.id_comments)}});
            return rows;
 });

trying to do it only with the find function is not possible, adding conditionals with table joins would complete the function.

**Comment by Lenn-xsr** [comment]
Thank you very much for the feedback, as soon as possible I will add a feature to complete this

**Comment by CarmenLexa** [comment]
there is another small detail, for example
if I only want a table to store configuration data which are data that do not need more rows, that is to say that they do not need a ID

{
  "theme_color":"#000000",
  "language":"en",
  "directory":"",
  "hidden":false,
  "blocked":false
}

are simple data that do not need an ID to be modified, just by specifying the object as well as read, if I use the find function, it returns the values as an array instead of an object, and automatically adds an ID when they are stored.

**Comment by CarmenLexa** [comment]
I have another problem, in a different table when saving, the IDs are duplicated.
[{
	"_id": 1648736626322,
	"user_alias": "aa",
}, {
	"_id": 1648736626322,
	"user_alias": "bb",
}, {
	"_id": 1648736626322,
	"user_alias": "nn",
}]

my shema file looks like this

const UserSchema = {
    _id: { type: Number, required: true },
    user_alias: {
        type: String,
    }
};

my code to store

 const { Schema } = new dbLocal({ path: DBSOURCE_LOCAL });
 const User= Schema("User",UserSchema);
  var params = {
            user_alias:req.body.user_alias
  }
  User.create(params).save();

I have 8 tables, and only in this table I have this duplicate ID problem

**Comment by Lenn-xsr** [comment]
> I have another problem, in a different table when saving, the IDs are duplicated. [{ "_id": 1648736626322, "user_alias": "aa", }, { "_id": 1648736626322, "user_alias": "bb", }, { "_id": 1648736626322, "user_alias": "nn", }]
> 
> my shema file looks like this
> 
> const UserSchema = { _id: { type: Number, required: true }, user_alias: { type: String, } };
> 
> my code to store
> 
> const { Schema } = new dbLocal({ path: DBSOURCE_LOCAL }); const User= Schema("User",UserSchema); var params = { user_alias:req.body.user_alias } User.create(params).save();
> 
> I have 8 tables, and only in this table I have this duplicate ID problem

I'm going to change this id system today, but I recommend you apply your own id, passing in `default`

for example: `default: Date.now()`

**Comment by Lenn-xsr** [comment]
> there is another small detail, for example if I only want a table to store configuration data which are data that do not need more rows, that is to say that they do not need a ID
> 
> { "theme_color":"#000000", "language":"en", "directory":"", "hidden":false, "blocked":false }
> 
> are simple data that do not need an ID to be modified, just by specifying the object as well as read, if I use the find function, it returns the values as an array instead of an object, and automatically adds an ID when they are stored.

About this, it was in my plans to change, for now the base of all the banks are an Array, I will change the base to be an Object, in this way, it facilitates the entry of simpler data like this

The recommendation I make is to use the database only for data that will be mutated/saved in bulk, data like this in your example could be saved in some other JSON

**Comment by Lenn-xsr** [comment]
> I have another problem, in a different table when saving, the IDs are duplicated. [{ "_id": 1648736626322, "user_alias": "aa", }, { "_id": 1648736626322, "user_alias": "bb", }, { "_id": 1648736626322, "user_alias": "nn", }]
> 
> my shema file looks like this
> 
> const UserSchema = { _id: { type: Number, required: true }, user_alias: { type: String, } };
> 
> my code to store
> 
> const { Schema } = new dbLocal({ path: DBSOURCE_LOCAL }); const User= Schema("User",UserSchema); var params = { user_alias:req.body.user_alias } User.create(params).save();
> 
> I have 8 tables, and only in this table I have this duplicate ID problem

There's a new update that solves this, just update to version [ [1.5.5](https://www.npmjs.com/package/db-local/v/1.5.5) ], we use the same MongoDB id creation system now.. so it will be unique :D

**Comment by CarmenLexa** [comment]
thanks for the updates and I made the changes and they work fine, I just need to add conditionals with combination of tables to the "find" function.

const datas = User.find((page) => page.cont_comment>0 , {tb_proxy:{ $ref: "Books", $id: item.id_books});

**Comment by Lenn-xsr** [comment]
I think everything is ok now, I just added the system with filter, just update to the latest version on npm [ [1.5.6](https://www.npmjs.com/package/db-local/v/1.5.6) ], example below

Example
```js
const Creators = Schema("Creators", {
  _id: { type: Number, required: true },
  name: { type: String, default: "Customer" },
});

const User = Schema("User", {
  _id: { type: Number, required: true },
  username: { type: String, default: "Customer" },
  creatorId: Number,
  bag: Array,
});

const datas = User.find((user) => user.bag.length > 2, {
  creator: { $ref: "Creators", $id: "$data.creatorId" },
});
```
Output
```js
[
  {
    _id: 1,
    username: 'Customer',
    bag: [ 1, 2, 3 ],
    creatorId: 1,
    creator: { _id: 1, name: 'Mango' }
  },
  {
    _id: 3,
    username: 'Customer 3',
    bag: [ 1, 2, 3, 4 ],
    creatorId: 3,
    creator: { _id: 3, name: 'Strawberry' }
  }
]
```

**Comment by CarmenLexa** [comment]
It would only need to store data that does not need an ID and does not need to be stored in an Array.
thanks for your help and for your patience now the module is the best module in npm local data storage.
