### ISSUE TITLE
Duplicate IDs persist

### ISSUE THREAD

**Issue by CarmenLexa** [Lenn-xsr/db-local#14]
hello good morning. i have again the problem of duplicate IDs when i clone a table row.

I have the following
const row = Campaign.find({
     _id: req.params.id,
})

 var pages = Campaign.create({
            name:row.name,
            time:row.time
 }).save();
       
 console.log("NEW ID: ",pages._id);

when doing this it only works fine once, but when sending several repetitive requests all the elements insert correctly but all with the same ID, only the first element to be duplicated has a different ID, the other elements do not.

**Comment by CarmenLexa** [comment]
my file looks like this
var CampaingSchema = {
  _id: { type: Number, required: true },
  name: {
    type: String,
  },
  time: { 
    type: String
  },
}

I noticed that the IDs are an alphanumeric string 6248a86e21fe3244b4286a77 , why add in schema the field type Number instead of String?

**Comment by Lenn-xsr** [comment]
I just performed an update that possibly solved your problem, just update to the latest version [ [1.5.7](https://www.npmjs.com/package/db-local/v/1.5.7) ].

but talking a little about the creation of id, at the moment the random generation of id, only occurs with String, if you want to generate with numbers, you would have to insert a function in the "default" of the object..

Examples below generation:

```js
// Number
const Campaing = Schema({
  _id: { type: Number, required: true, default: Date.now() },
  name: String,
  time: String,
})

// Output ex.: { "_id": 1649860409661 }

// String
const Campaing = Schema({
  _id: String, // It is not necessary to pass anything, by default the properties are already inserted: default and required
  name: String,
  time: String,
})

// Output ex.: { "_id": "6256df4ab506e014ac86100c" }
```

I'll be waiting for your answer to know if everything went well :D
