### ISSUE TITLE
Duplicate IDs still persist in mass storage

### ISSUE THREAD

**Issue by CarmenLexa** [Lenn-xsr/db-local#15]
Sorry for my delay, I tried the new update this way.
`const dbLocal = require("db-local");
const { Schema } = new dbLocal({ path: "./databases" });

const User = Schema("User", {
    _id: { type: Number, required: true, default: Date.now() },
    username: { type: String, default: "Customer" },
    lastname: { type: String, default: "Smith" },
});

for(var a =0; a<20; a++){
    var name = Math.random().toString(36).replace(/[^a-z]+/g, '').substring(0, 5);
    var last = Math.random().toString(36).replace(/[^a-z]+/g, '').substring(0, 5);
    User.create({username: name,tag: last}).save();
}
`
in the previous version, I did it with express and jquery but I had to add an ID to save all the data with a unique ID.
another missing function is how to import and export tables :)

**Comment by Lenn-xsr** [comment]
Try this code
```js
const dbLocal = require("db-local");
const { Schema } = new dbLocal({ path: "./databases" });

const User = Schema("User", {
  _id: String,
  username: { type: String, default: "Customer" },
  lastname: { type: String, default: "Smith" },
});

for(let a = 0; a < 20; a++){
  const name = Math.random().toString(36).replace(/[^a-z]+/g, '').substring(0, 5);
  const last = Math.random().toString(36).replace(/[^a-z]+/g, '').substring(0, 5);
  User.create({ username: name, tag: last }).save();
}
```

**Comment by CarmenLexa** [comment]
I have another problem when creating an executable with PKG
I get the following error when compiling
`
F:\ProyectoKong\BrowserBear\node_modules\db-local\lib\utils.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot include directory %1 into executable.
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\utils.js
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\methods.js
> Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js
`
and when I run the application with CMD window it shows me this error

`
C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js:27
    (schema?._id?.type === Number && !schema?._id?.default)
            ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Module._compile (pkg/prelude/bootstrap.js:1758:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\snapshot\BrowserBear\node_modules\db-local\lib\index.js:1:78)
`

**Comment by Lenn-xsr** [comment]
> 

I verified that it was my error in the execution of unique IDs, try to update the package to the latest version [ [1.6.7](https://www.npmjs.com/package/db-local/v/1.6.7) ] and run following the code below

```js
const dbLocal = require("./lib");
const { Schema } = new dbLocal({ path: "./databases" });

const User = Schema("User", {
  _id: String,
  username: { type: String, default: "Customer" },
  lastname: { type: String, default: "Smith" },
});

for (let a = 0; a < 10; a++) {
  const randomText = () =>
    Math.random()
      .toString(36)
      .replace(/[^a-z]+/g, "")
      .substring(0, 5);

  User.create({
    username: randomText(),
    lastname: randomText(),
  }).save();
}
```

Output
![code](https://user-images.githubusercontent.com/55673351/163834811-d0f7ae30-0ab7-4c32-ab6a-e1e1a4ba6f8c.png)

**Comment by Lenn-xsr** [comment]
> I have another problem when creating an executable with PKG I get the following error when compiling ` F:\ProyectoKong\BrowserBear\node_modules\db-local\lib\utils.js Dynamic require may fail at run time, because the requested file is unknown at compilation time and not included into executable. Use a string literal as an argument for 'require', or leave it as is and specify the resolved file name in 'scripts' option.
> 
> > Warning Cannot include directory %1 into executable.
> > Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\utils.js
> > Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\methods.js
> > Warning Failed to make bytecode node10-x86 for file C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js
> > `
> > and when I run the application with CMD window it shows me this error
> 
> ` C:\snapshot\BrowserBear\node_modules\db-local\lib\modules\schema.js:27 (schema?._id?.type === Number && !schema?._id?.default) ^
> 
> SyntaxError: Unexpected token . at Module._compile (internal/modules/cjs/loader.js:721:23) at Module._compile (pkg/prelude/bootstrap.js:1758:32) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) at Module.load (internal/modules/cjs/loader.js:651:32) at tryModuleLoad (internal/modules/cjs/loader.js:591:12) at Function.Module._load (internal/modules/cjs/loader.js:583:3) at Module.require (internal/modules/cjs/loader.js:690:17) at Module.require (pkg/prelude/bootstrap.js:1676:31) at require (internal/modules/cjs/helpers.js:25:18) at Object. (C:\snapshot\BrowserBear\node_modules\db-local\lib\index.js:1:78) `

This could be the node.js version, the operator giving error, [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), was recently added in node. try updating to see if it resolves the error
