### ISSUE TITLE
Problem with relating a table from an array

### ISSUE THREAD

**Issue by CarmenLexa** [Lenn-xsr/db-local#17]
Hello again :)
I am trying to get all the data of a table from an array containing student IDs according to their scores.
I have the following: 
![code_1](https://user-images.githubusercontent.com/60371152/166961492-cff4a0a5-ee22-4a0c-860e-c372cc33370c.png)

when saving the data in the Course table I have the following:

![code_2](https://user-images.githubusercontent.com/60371152/166961600-bb3d023e-6fba-418d-a1ff-8ab6fb023bd9.png)

try to do the following but it does not work
![code_3](https://user-images.githubusercontent.com/60371152/166961974-481fa6f7-06ac-4cc5-b091-bfd4ee8c76ba.png)

using the find method I don't know how to iterate the ID array to get the data from the student table which is also related to the subject table. 
I also have to add a conditional to obtain only the students who have a score higher than 8.

**Comment by CarmenLexa** [comment]
@Lenn-xsr any news?

**Comment by Lenn-xsr** [comment]
@CarmenLexa Sorry, I was busy with other projects, this week I will update the package putting this new feature.

**Comment by Lenn-xsr** [comment]
Hi @CarmenLexa, I ended up doing the update today, and by my tests it is in accordance with what you wanted, try to update the package to the latest version [ [1.7.8](https://www.npmjs.com/package/db-local/v/1.7.8) ] and run your code again :D

I'll be waiting for your return to see if everything went well.

**Comment by CarmenLexa** [comment]
thank you for your patience @Lenn-xsr 
it works! it shows me all the data, but when I add the join of another table in this way, I can see all the data.

`
 const datas = Course.find({tb_teacher: { $ref: "Teacher", $id: { $data: "id_teacher" } },tb_students:{ $ref: "Student", $id: { $data: "id_students" }, tb_subjects:{ $ref: "Subjects", $id: { $data: "id_subjects" } } }});
`
seems to work as well, but there are IDS where your data is not shown complete, i.e. the "tb_subjects" row is not always displayed. 

Now how can I add a conditional? I want to separate by age and by score in the "Student" table.

**Comment by Lenn-xsr** [comment]
> 

Glad it all worked out @CarmenLexa ...

About your question, could you give me a complete example, showing how it would be passed in the find and the return that would possibly come out?

At the moment we don't have a system to separate/filter, but I could add..

**Comment by CarmenLexa** [comment]
shows me this way
`
 
![students](https://user-images.githubusercontent.com/60371152/170081452-4a398566-ec38-4719-99b2-b86f619e6c24.png)

`

but it is not always the case, after several attempts it shows me the right thing to do

![students_2](https://user-images.githubusercontent.com/60371152/170081596-2b537e9b-901c-4faf-bcf9-d6029708a606.png)

I have to filter the values if there are students with lower scores.

**Comment by Lenn-xsr** [comment]
I closed this issue and opened another one, since we are going to start talking about another system to be created!

In advance, I apologize for the delay, I'm very busy with other projects and I don't have time to update this one, soon I'll bring new updates..

https://github.com/Lenn-xsr/db-local/issues/18#issue-1265209939
