### ISSUE TITLE
_id auto increment

### ISSUE THREAD

**Issue by borodadada** [Lenn-xsr/db-local#19]
hi! can possible use auto increment for _id ?

**Comment by Lenn-xsr** [comment]
Hey! Could you give me an example of what it would be like?

**Comment by Lenn-xsr** [comment]
> hi! can possible use auto increment for _id ?

Hey! Could you give me an example of what it would be like?

**Comment by borodadada** [comment]
For example, if I add a user to the database, I do not have to think about _id, it is calculated automatically.
```
Mysql What is an AUTO INCREMENT Field?
Auto-increment allows a unique number to be generated automatically when a new record is inserted into a table.

Often this is the primary key field that we would like to be created automatically every time a new record is inserted.
```
This is convenient, one less field to fill.

**Comment by Lenn-xsr** [comment]
> 

The db already does this, when you define a schema and don't put the _id, it automatically defines it, [see this reference](https://github.com/Lenn-xsr/db-local/blob/master/lib/modules/schema.js#L26)

The case would be different if you wanted to generate an id standardized by length, for example:
`_id: 1, _id: 2, _id: 3...`
In this case for now we don't have this one in the example, but it would be easy to do

**Comment by Lenn-xsr** [comment]
> For example, if I add a user to the database, I do not have to think about _id, it is calculated automatically.
> 
> ```
> Mysql What is an AUTO INCREMENT Field?
> Auto-increment allows a unique number to be generated automatically when a new record is inserted into a table.
> 
> Often this is the primary key field that we would like to be created automatically every time a new record is inserted.
> ```
> 
> This is convenient, one less field to fill.

The db already does this, when you define a schema and don't put the _id, it automatically defines it, [see this reference](https://github.com/Lenn-xsr/db-local/blob/master/lib/modules/schema.js#L26)

The case would be different if you wanted to generate an id standardized by length, for example:
`_id: 1, _id: 2, _id: 3...`
In this case for now we don't have this one in the example, but it would be easy to do it in your code itself (separated from the database).

This type of update would only be able to come out, when I changed the database base, from Array to an Object, for some reasons of logic.

**Comment by borodadada** [comment]
thx man, i got it
