### ISSUE TITLE
find by part

### ISSUE THREAD

**Issue by borodadada** [Lenn-xsr/db-local#20]
is it possible to search by part of the text?
example
```
{ user: 'nickname', more: 'big head man' }
```
can i find this user if use only part - big in more ?

**Comment by Lenn-xsr** [comment]
> is it possible to search by part of the text? example
> 
> ```
> { user: 'nickname', more: 'big head man' }
> ```
> 
> can i find this user if use only part - big in more ?

Try using the filter "$in" ( case sensitive )
```js
{ user: 'nickname', more: { $in: 'big head man' } }
```

Edit.:

You can use the filter with "$regex", it would be better and insensitive (if you want it that way)
```js
User.find({ user: "nickname", more: { $regex: new RegExp('big head man', 'i') } })
```


You can find more filters in the [documentation](https://lenn.gitbook.io/db-local/methods/find/filters)

**Comment by borodadada** [comment]
thx man!
