### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Guaxinim5573** [Lenn-xsr/db-local#6]
Unit Testing makes it easy to find bugs in code when someone is contributing since it's easy when debugging.

[Mocha](https://mochajs.org) with [Chai](https://www.npmjs.com/package/chai) or [Jest](https://jestjs.io) is easy to develop and provide a lot of benefits.

**Comment by ghost** [comment]
I believe there isn't need to create unit tests for a database.

**Comment by Guaxinim5573** [comment]
I don't think so.

Tests help when contributing and finding bugs more easily.
Some databases like [mongoose](https://github.com/Automattic/mongoose/tree/master/test), [firebase](https://github.com/firebase/firebase-js-sdk#running-the-tests), [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3/tree/master/test), [lowdb](https://github.com/typicode/lowdb/blob/main/src/Low.test.ts) and [quick.db](https://github.com/lorencerri/quick.db/blob/master/spec/test.js) have some type of testing.
